# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS Applicant Form' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Applicant Form
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'iOS Applicant FormTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS Applicant FormUITests' do
    # Pods for testing
  end

end
